---
config:
  theme: base
  themeVariables:
    fontFamily: "Arial"
    primaryColor: "#4FD2DB"
    primaryTextColor: "#245D61"
    lineColor: "#245D61"
    secondaryColor: "#245D61"
    background: "#F4FBFA"
---
xychart-beta
    title "Exportaciones e importaciones: adaptación didáctica de William Playfair"
    x-axis [Inglaterra, Francia, Holanda, España]
    y-axis "Valor" 0 --> 100
    bar [85, 70, 55, 40]
    bar [65, 52, 44, 28]